# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Localization tips
email: nathan@loc.tips
description: >
  Tired of reading dry 'localization best practices' writups?
  Do you find yourself explaining why concatenation is bad until you're blue in the face?
  Then this site is for you. A localization tips site for the curious, the jaded, and the
  out of time for that presentation this afternoon
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.loc.tips" # the base hostname & protocol for your site
twitter_username: #jekyllrb
github_username:  #jekyll
port: 3000
sass:
  style: compressed

# Build settings
markdown: kramdown
